apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apporto-tenants
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/yousmakhayyam/Apporto-demo-k8s-gitops.git
      revision: main
      directories:
      - path: tenants/*/primary-01/*
  template:
    metadata:
      name: "{{path[2]}}-{{path[3]}}-{{path[3]}}-{{path[4]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/yousmakhayyam/Apporto-demo-app-nginx.git
        path: helm
        helm:
          valueFiles:
          - tenants/{{path[1]}}/{{path[2]}}/{{path[3]}}/{{path[4]}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[3]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true